### ISSUE TITLE
design an ldats function

### ISSUE THREAD

**Issue by DAPPERstats** [weecology/LDATS#10]
for the purposes of reusing and scaling the methodology, I think it will be good to have an ldats() function that runs both the LDA and timeseries chunks and then (after running long models) spits out an answer of "has the community structure changed, and if so, how?"

this requires us linking the two parts and automating some of the stuff that's being hand-held right now (so we're covering the likelihood surfaces appropriately, for example).
we'll need to do some testing to support that automation

but we also need to design the function interface (arguments and classes). so from a user perspective, what are we thinking we'd like in it? (@davharris @emchristensen @davharris @ha0ye )

**Comment by ha0ye** [comment]
I don't think I know enough about the method to comment on arguments for the functions right now.

I do think the format of the input data should be fairly flexible (i.e. data.frame, matrix), and for that to be well-specified somewhere. Related to that is an open question about whether to build in support for one of the time-aware tibble formats (see https://github.com/weecology/MATSS-community-change/issues/7). [If we decide to choose one or the other, that also provides an easy solution to the aggregation-by-season feature in portalr: https://github.com/weecology/portalr/issues/64, cc @bleds22e]

**Comment by DAPPERstats** [comment]
full working draft done w #32 
still work to be done on pulling through the right output, but the pipeline is set up, so i'm closing this issue
