### ISSUE TITLE
LDATS dependent on rlang>=0.3.1?

### ISSUE THREAD

**Issue by ethanwhite** [weecology/LDATS#104]
I couldn't get the MATSS-pipeline script to run. That appeared to be triggered by `LDATS::LDA_controls_list()` erroring on `rlang `3.0.1`. After updating everything works. If all of this is real the dependency should be updated to reflect this limitation.

**Comment by juniperlsimonis** [comment]
oh, hmm, i think it might be. 
in looking at my session info where i've built it, it looks like i have v 0.3.1 of rlang (i assume that's what you mean rather than 3.0.1?). thanks for catching this!

**Comment by ethanwhite** [comment]
Yeah, `0.3.1`. I do seem to have a way of tripping over edge cases...

**Comment by juniperlsimonis** [comment]
addressed in #110
