### ISSUE TITLE
LDATS Team Check

### ISSUE THREAD

**Issue by juniperlsimonis** [weecology/LDATS#112]
Check yourself off when you've completed your evaluation of v0.1.0
- [x] @juniperlsimonis 
- [x] @emchristensen 
- [ ] @davharris 
- [x] @diazrenata 
- [x] @ha0ye 
- [ ] @ethanwhite 
- [ ] @skmorgane

**Comment by juniperlsimonis** [comment]
(see the message in the slack channel for details!)

**Comment by emchristensen** [comment]
looks awesome! I tried out the vignettes, but I can't get them to run because LDA_set and select_LDA are not exported objects -- am I doing it wrong?

**Comment by diazrenata** [comment]
Hmm - my first question would be, do you have the most recent version of
LDATS installed?

**Comment by emchristensen** [comment]
I ran what was in the vignette: 
devtools::install_github('weecology/LDATS')

**Comment by juniperlsimonis** [comment]
are you trying to build the vignette or just run the displayed code? (and which of the vignettes?)

also, can you run the code that's in the README successfully? it's set up with a call to `library` but you can run it as 

```
data(rodents, package = "LDATS")
dtt <- rodents$document_term_table
dct <- rodents$document_covariate_table
weights <- LDATS::document_weights(dtt)
TS_controls <- LDATS::TS_controls_list(timename = "newmoon")
controls <- LDATS::LDA_TS_controls_list(TS_control = TS_controls)
r_LDATS <- LDATS::LDA_TS(dtt, dct, topics = 2:5, nseeds = 2, 
                  formulas = c(~1, ~newmoon), nchangepoints = 0:2,
                  weights = weights, control = controls)
```
instead (i.e. avoiding the `library` call and instead only pulling the specific functions)

**Comment by emchristensen** [comment]
I was just running the code from the vignettes, I'm not sure what you mean by build. (I got the same warnings from both vignettes)

The code in the README works fine

**Comment by juniperlsimonis** [comment]
got it, thanks! by build i mean like rendering the Rmd files of the vignettes (e.g. running `devtools::build_vignettes()`)

ok, so let's start with the rodents example vignette. it's functionally quite similar to what's in that README, so we should be able to track that down. it looks like there's not a `library` call and there's no `LDATS::` happening either, so I wonder if it's that the package isn't loaded?

**Comment by emchristensen** [comment]
ok, I did the build_vignettes thing and then tried running the code again and now it works. clearly R is messing with me today.

**Comment by juniperlsimonis** [comment]
oh! sorry for the confusion! i didn't mean you should build them, was just wondering if that's what you did or if you were just running the visible code. we won't expect users to rebuild the vignettes, but definitely want them to be able to run the visible code (which is I think what you were failing on, right?).

so, in a fresh environment, if you don't build the vignettes, can you not run the code that's visible in the vignette?

**Comment by emchristensen** [comment]
hmm my computer has now stopped doing things on a number of levels, I'm going to take it as a sign that it's done for the day and come back to this tomorrow... (it's not a very youthful computer. it's entirely possible that my issues are unique and because of this machine)

**Comment by emchristensen** [comment]
aaaand it works today. I don't know exactly what changed but thanks for helping me out!

**Comment by juniperlsimonis** [comment]
woo hoo! for sure! thanks for testing it out!
