### ISSUE TITLE
Polish up work on paper-comparison vignette for submission to ReScience Journal

### ISSUE THREAD

**Issue by ha0ye** [weecology/LDATS#125]
I think we probably only need a bit more work to make something submission-ready. Thoughts from @juniperlsimonis, @diazrenata, @emchristensen ?

**Comment by juniperlsimonis** [comment]
just to be clear, you mean submitting the vignette (not the package, which will have a JOSS submission probably?) and to this journal (http://rescience.github.io/)?

**Comment by ha0ye** [comment]
Yup!

**Comment by juniperlsimonis** [comment]
closing this issue as it seemed like it was something that we decided against, but correct me if i'm wrong, @diazrenata

**Comment by diazrenata** [comment]
:+1: I think we decided to wait at least until I interact with them some wrt another project, especially given that we're close collaborators with the original project authors.
