### ISSUE TITLE
Processing non-integer timesteps

### ISSUE THREAD

**Issue by diazrenata** [weecology/LDATS#126]
See https://github.com/weecology/MATSS-LDATS/issues/13.

The LDA needs the `timename` column to be integers. We could build in some functionality to assign integer values to non-integer timesteps and convert back?

**Comment by diazrenata** [comment]
@diazrenata identify the problem datasets in MATSS

**Comment by diazrenata** [comment]
Ok, so turns out the only non-integer timesteps in MATSS so far have years in increments of .5. So nothing too intense!

See: https://github.com/weecology/MATSS-LDATS/blob/check_time_data/analysis/reports/time_check.md

**Comment by ha0ye** [comment]
@diazrenata Was this the Jornada data?

**Comment by diazrenata** [comment]
SGS and the jornada.

I’m not at my computer right now and I don’t 100% remember how I set up the
error handling, but I think as long as it doesn’t throw a complete halting
error it should be easy to tweak if necessary.

I’m pretty sure MATSS-LDATS does try to coerce to integers. I can track the
specifics down in a little bit!

**Comment by ha0ye** [comment]
Yeah, it would be good to know how you're doing it. I think `tidyr::full_seq()` is likely a good option to do that, which means I can add `period` to the metadata for SGS and Jornada, and update the data checks and tests.

**Comment by diazrenata** [comment]
You could just go for it? Whatever I did was just a stopgap to keep the
pipeline from failing with a footnote saying to do something permanent
later :P

**Comment by ha0ye** [comment]
Ok, I'll work on:
* adding `period = 0.5` to the metadata for SGS and Jornada
* updating data checking functions

and then I think we can defer working on the processing code ~ weecology/MATSS#96 until after we discuss implementation details

**Comment by diazrenata** [comment]
lol, MATSS-LDATS checks if the timename column *could* be swapped for a timesteps column that is just the row numbers, and complains if it can't, but makes no attempt to actually *make* that change. (Because when I wrote it the only outcome that was actually happening was that you couldn't make the change). 

If MATSS::check_data_format and MATSS-LDATS's data checking function (which checks that $timename exists and checks if the timename column is integers) fail, it just skips the TS model.

**Comment by ha0ye** [comment]
@diazrenata Here's a proposed implementation - https://github.com/weecology/MATSS/issues/136
Would that work for you to modify the pipeline in MATSS-LDATS?

**Comment by juniperlsimonis** [comment]
i'm going to fold this into the other issue on data helper functions, as that's the general concept that the time issue falls under
