### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by DAPPERstats** [weecology/LDATS#13]
I think we need to make a decision about what we want to name this R package, especially if we're submitting it to CRAN (which I think we should)

currently the repo name is "LDATS" (as in Latent Dirichlet Analysis Time Series)
@ha0ye came up with LDA.breakpoint, which while great in its Johnny Utah nature, is a bit long and a bit restrictive in its name (Hao, what was your impetus behind that name?)

One of the things I'm thinking about here is the generality of our package both now and into the future. 

With the addition of the 0-change point model (already included!) and @skmorgane 's request for the capacity for smooth change through time (not yet included!), the package can end up fitting an LDA that has no change at all in time, or has a continuous change, rather than a break point. 

Regardless of the specifics of the 2nd stage (temporal model), I do see the package staying targeted at temporal data for the time being, but I could definitely see this expanding beyond that. For example, what if someone were interested in spatial distributions (like Valle's paper that motivated Erica and Dave)? 

As for the LDA part, right now that is what we're using, but I could see us expanding the scope of the topic models included (e.g. correlated topic models, structural topic models.

My thought right now is that the core component of the package is a two-stage topic model, so I'm wondering what folks think about "tstm" or "tmts", both of which are available on CRAN.

As a ref: hadley's suggestions on the topic: http://r-pkgs.had.co.nz/package.html#naming

**Comment by DAPPERstats** [comment]
I guess one of the key questions here is whether we see this as a "done and done" package (in which case a specific name is fine) or we expect to keep building it out into the future (in which case we want a more general name)

**Comment by ha0ye** [comment]
I think I wanted both LDA and changepoint in the name, and then I let my mind make the leap from changepoint -> breakpoint -> pointbreak.

If one future goal is to build functionality on top of the package, that can be done with a new package that refers to this one as a dependency. So I don't think we necessarily need a name that signifies anything broader than STM or LDA.

**Comment by DAPPERstats** [comment]
given the flexibility on the time side of things, I think we should go with LDATS as a package name. CHanging the LDA part would be substantial enough to have a new package that references this one, but the time series stuff is already general enough beyond break points, so I think we should use the name of the repo as the package name as well. I'm going to change it to that for now, if folks want to discuss and such, we can totally revisit this, though.
