### ISSUE TITLE
Check various dependencies

### ISSUE THREAD

**Issue by ha0ye** [weecology/LDATS#24]
I think some of the R code may be using imports from other packages that aren't documented in the NAMESPACE. 

Looks like the ones at the top of `working_space.R`
```
"%>%" <- dplyr::"%>%"
"period" <- lubridate::"period"
"%dopar%" <- foreach::"%dopar%"
"%dorng%" <- doRNG::"%dorng%"
```

Suggested fix, use Roxygen to note these so that `devtools::document` or `roxygen::roxygenize` will auto-create the appropriate `NAMESPACE` file.

Somewhere in one of the `.R` files (could even be `zzz.R`), include:
```
#' @importFrom magrittr "%>%"
#' @importFrom lubridate "period"
#' @importFrom foreach "%dopar%"
#' @importFrom doRNG "%dorng%"
```

**Comment by DAPPERstats** [comment]
done w #30 by including the packages actually needed (only magrittr and doParallel) as "Depends" rather than "Imports", which attaches the packages and thereby provides access to the functions (namely here `%>%` and `%dopar%`) without needing to use `::`.

note that using 
```
#' @importFrom magrittr "%>%"
```
for example, didn't work without also including 
```
"%>%" <- magrittr::"%>%"
```

**Comment by ha0ye** [comment]
Hmm, I feel like the `importFrom` should have done it... Did it add lines to `NAMESPACE` when you ran `devtools::document()`?

**Comment by DAPPERstats** [comment]
I know, I thought so too, but it was't. 
Yeah, it added lines to `NAMESPACE` but it still was telling me it didn't know what those functions were.

**Comment by DAPPERstats** [comment]
ohhhhhhhhhhhhhh i thought `%dopar%` was from `doParallel` but it's from `foreach`. that was causing it to not be imported properly.
