### ISSUE TITLE
Allow trends between changepoints

### ISSUE THREAD

**Issue by skmorgane** [weecology/LDATS#8]
@davharris & @emchristensen had done some early development of a version of the model that allowed trends between changepoints so that the model could capture gradual directional changes. This should be added to the package.

**Comment by DAPPERstats** [comment]
oooh, yes! @davharris and @emchristensen is that code somewhere I have access to/can you point me to it?

**Comment by davharris** [comment]
I'm not sure if it ever got committed and/or to which repo.  But the implementation was simple enough that I don't thin you'll need it: instead of just `y~sin(t) + cos(t)` in the multinomial model, we added `+ t`.

**Comment by DAPPERstats** [comment]
oh totally. thanks!

**Comment by DAPPERstats** [comment]
@skmorgane would a linear term on top of the seasonal dynamic be sufficient, or would you want a more general or broader set of options for those kinds of changes?

**Comment by skmorgane** [comment]
ok, I rediscovered this issue! Yes, I think it makes sense to start with a linear term. At some point it might be crazy fun to figure out a way to quantify how the rate of change varies through time, but let's start with adding a way to pick up the presence of gradual change (or non-extremely rapid change).

**Comment by DAPPERstats** [comment]
draft is done w #22
I think we'll want to likely be able to bring more of the results from the models upwards, but the fitting now allows for flexible continuous impacts (e.g., based on time) between change points
